Repository mozmeao/springfield, pull requests merged in 2025-06, with the labels that each got.

#227 Fix ftl string and remove globe on no-js lang switcher (fixes #225)
  l10n/en/footer-firefox.ftl
  media/css/protocol/components/_footer.scss
Labels: Awaiting Review

#230 Sweep links (fixes #228)
  l10n/en/brands.ftl
  l10n/en/firefox/features/private-browsing-2023.ftl
  springfield/firefox/templates/firefox/features/private-browsing.html
  springfield/firefox/templates/firefox/includes/desktop-platform-sub-nav.html
  springfield/firefox/templates/firefox/includes/sub-nav-firefox.html
  springfield/firefox/templates/firefox/more/best-browser.html
  springfield/firefox/templates/firefox/releases/notes.html
Labels: Awaiting Review

#272 (fix) Stop creating a redirect loop when a draft page matches a URL path - it should correctly 404
  springfield/cms/middleware.py
  springfield/cms/tests/test_middleware.py
Labels: Awaiting Review

#273 (fix) Port fix from Bedrock to stop /all being crawled
  springfield/firefox/templates/firefox/all/base.html
Labels: Awaiting Review

#276 (fix) Handle edge case in locale-list building when prefer_cms is used but there is nothing yet in the CMS
  springfield/base/templatetags/helpers.py
  springfield/base/tests/test_helpers.py
Labels: Awaiting Review

#238 Add download icon to download button (fixes #205)
  media/css/protocol/components/_download-button.scss
  media/img/icons/m24-small/download-white.svg
  springfield/firefox/templates/firefox/all/download.html
  springfield/firefox/templates/firefox/enterprise/index.html
  springfield/firefox/templates/firefox/includes/download-button-thanks.html
  springfield/firefox/templates/firefox/includes/download-button.html
  springfield/firefox/templates/firefox/includes/macros.html
Labels: Frontend, Awaiting Review

#264 Fix outdated product features dropping MR106/MR2 switch logic
  media/img/firefox/download/desktop/color-ways.svg
  media/img/firefox/download/desktop/dark-mode.svg
  media/img/firefox/download/desktop/lock.svg
  springfield/firefox/templates/firefox/download/desktop/download.html
Labels: Awaiting Review

#259 Eliminate repetitive wordmarks
  l10n/en/firefox/download/desktop.ftl
  media/css/firefox/download/basic/download.scss
  media/css/firefox/download/desktop/download.scss
  media/css/firefox/home-en-us-ca.scss
  springfield/firefox/templates/firefox/download/basic/base_download.html
  springfield/firefox/templates/firefox/download/desktop/download-en-us-ca.html
  springfield/firefox/templates/firefox/download/desktop/download.html
Labels: Frontend, Awaiting Review

#298 remove pencil banner site link (fix #296)
  l10n/en/banners/m24-pencil-banner.ftl
  springfield/base/templates/includes/banners/pencil-banner.html
Labels: Frontend, Awaiting Review

#304 Update qr code utm source
  springfield/firefox/templates/firefox/browsers/mobile/includes/s2d-android.html
Labels: Awaiting Review

#326 Fix home mobile #next anchor for refresh locales
  springfield/firefox/templates/firefox/download/desktop/download-en-us-ca.html
Labels: P1

#329 Only bind pencil-banner setup if it has close button
  media/js/base/banners/m24-pencil-banner.es6.js
Labels: Frontend, Awaiting Review
