Repository mozmeao/springfield, pull requests merged in 2025-08, with the labels that each got.

#394 fix homepage release section rtl and mobile styles (fix #389)
  media/css/firefox/home.scss
Labels: Frontend, Needs Review

#413 Fixup failing tests for features/translate changeset
  springfield/firefox/templates/firefox/features/translate.html
  springfield/firefox/views.py
Labels: P1, Needs Review

#415 Fix typeof check for MzpSupports object in navigation Fix #380
  media/js/base/protocol/navigation.es6.js
Labels: Frontend, P1, Needs Review

#288 Add "Features" menu dropdown
  l10n/en/navigation-firefox.ftl
  media/css/m24/components/navigation-refresh.scss
  media/img/icons/caret-sprite.svg
  springfield/base/templates/403_csrf.html
  springfield/base/templates/includes/navigation/menus/features.html
  springfield/base/templates/includes/navigation/menus/resources.html
  springfield/base/templates/includes/navigation/navigation.html
Labels: Frontend, Needs Review

#417 Fix result contamination in Playwright when looping pages
  tests/playwright/specs/products/firefox/firefox-features.spec.js
Labels: Frontend, Infra

#403 port landing/tech, education, gaming pages from bedrock (fix #383)
  media/css/firefox/landing/index.scss
  media/css/protocol/components/_sub-navigation.scss
  media/img/firefox/landing/education/hero-1000.png
  media/img/firefox/landing/education/hero-400.png
  media/img/firefox/landing/education/hero-600.png
  media/img/firefox/landing/education/hero-800.png
  media/img/firefox/landing/education/icon-language-tool-128.png
  media/img/firefox/landing/education/icon-language-tool-64.png
  media/img/firefox/landing/education/icon-privacy.svg
  media/img/firefox/landing/education/icon-productivity.svg
  media/img/firefox/landing/education/icon-search.svg
  media/img/firefox/landing/education/icon-tomato-clock-128.png
  media/img/firefox/landing/education/icon-tomato-clock-64.png
  media/img/firefox/landing/education/icon-unhook-128.png
  media/img/firefox/landing/education/icon-unhook-64.png
  media/img/firefox/landing/education/og.png
  media/img/firefox/landing/education/students-1000.png
  media/img/firefox/landing/education/students-1200.png
  media/img/firefox/landing/education/students-400.png
  media/img/firefox/landing/education/students-600.png
  media/img/firefox/landing/education/students-800.png
  media/img/firefox/landing/gaming/gamers-1000.png
  media/img/firefox/landing/gaming/gamers-1200.png
  media/img/firefox/landing/gaming/gamers-400.png
  media/img/firefox/landing/gaming/gamers-600.png
  media/img/firefox/landing/gaming/gamers-800.png
  media/img/firefox/landing/gaming/hero-1000.png
  media/img/firefox/landing/gaming/hero-400.png
  media/img/firefox/landing/gaming/hero-600.png
  media/img/firefox/landing/gaming/hero-800.png
  media/img/firefox/landing/gaming/icon-augmented-steam-128.png
  media/img/firefox/landing/gaming/icon-augmented-steam-64.png
  media/img/firefox/landing/gaming/icon-bitwarden-128.png
  media/img/firefox/landing/gaming/icon-bitwarden-64.png
  media/img/firefox/landing/gaming/icon-customize.svg
  media/img/firefox/landing/gaming/icon-enhancer-128.png
  media/img/firefox/landing/gaming/icon-enhancer-64.png
  media/img/firefox/landing/gaming/icon-privacy.svg
  media/img/firefox/landing/gaming/icon-stream.svg
  media/img/firefox/landing/gaming/og.png
  media/js/base/consent/allow-list.es6.js
  media/js/firefox/landing/init.es6.js
  media/js/firefox/landing/partner-build-download-init.es6.js
  media/js/firefox/landing/partner-build-download.es6.js
  media/static-bundles.json
  springfield/firefox/templates/firefox/landing/education.html
  springfield/firefox/templates/firefox/landing/gaming.html
  springfield/firefox/templates/firefox/landing/tech.html
  springfield/firefox/urls.py
  tests/unit/spec/base/datalayer-productdownload.js
  tests/unit/spec/firefox/landing/partner-build-download.js
Labels: Frontend

#419 Fixup fx/landing asset paths
  media/css/firefox/landing/index.scss
Labels: P1
