Repository mozmeao/springfield, pull requests merged in 2025-07, with the labels that each got.

#290 Sweep external mozorg links for UTM params (fixes #232)
  springfield/base/templates/404.html
  springfield/base/templates/500.html
  springfield/base/templates/includes/footer/footer.html
  springfield/base/templates/includes/navigation/menus/resources.html
  springfield/base/templates/includes/navigation/nav-cta.html
  springfield/firefox/templates/firefox/all/base.html
  springfield/firefox/templates/firefox/browsers/compare/base-article.html
  springfield/firefox/templates/firefox/browsers/compare/brave.html
  springfield/firefox/templates/firefox/browsers/compare/chrome.html
  springfield/firefox/templates/firefox/browsers/compare/edge.html
  springfield/firefox/templates/firefox/browsers/compare/opera.html
  springfield/firefox/templates/firefox/browsers/compare/safari.html
  springfield/firefox/templates/firefox/browsers/desktop/base.html
  springfield/firefox/templates/firefox/browsers/desktop/chromebook.html
  springfield/firefox/templates/firefox/browsers/desktop/index.html
  springfield/firefox/templates/firefox/browsers/mobile/index.html
  springfield/firefox/templates/firefox/channel/android.html
  springfield/firefox/templates/firefox/channel/desktop.html
  springfield/firefox/templates/firefox/default/thanks.html
  springfield/firefox/templates/firefox/developer/index.html
  springfield/firefox/templates/firefox/download/basic/base_download.html
  springfield/firefox/templates/firefox/download/basic/thanks.html
  springfield/firefox/templates/firefox/download/desktop/download-en-us-ca.html
  springfield/firefox/templates/firefox/download/desktop/download.html
  springfield/firefox/templates/firefox/download/desktop/thanks.html
  springfield/firefox/templates/firefox/enterprise/index.html
  springfield/firefox/templates/firefox/features/add-ons.html
  springfield/firefox/templates/firefox/features/customize.html
  springfield/firefox/templates/firefox/features/fast-2024.html
  springfield/firefox/templates/firefox/features/password-manager.html
  springfield/firefox/templates/firefox/features/private-browsing.html
  springfield/firefox/templates/firefox/features/private.html
  springfield/firefox/templates/firefox/features/sync.html
  springfield/firefox/templates/firefox/features/tips/tips.html
  springfield/firefox/templates/firefox/includes/download-button-thanks.html
  springfield/firefox/templates/firefox/includes/download-button.html
  springfield/firefox/templates/firefox/includes/macros.html
  springfield/firefox/templates/firefox/includes/mozilla-account-promo.html
  springfield/firefox/templates/firefox/includes/send-to-device.html
  springfield/firefox/templates/firefox/more/best-browser.html
  springfield/firefox/templates/firefox/more/faq.html
  springfield/firefox/templates/firefox/testflight.html
  springfield/newsletter/templates/newsletter/includes/form.html
  springfield/privacy/templates/privacy/cookie-settings.html
Labels: P3, Post launch

#353 Remove Pocket mentions
  .github/l10n/linter_config.yml
  l10n/en/firefox/browsers/mobile/android.ftl
  l10n/en/firefox/browsers/mobile/ios.ftl
  l10n/en/mozilla-account-promo.ftl
  media/img/firefox/features/tips/fx_video-thumb_secret-menu_pocket_amy.jpg
  springfield/firefox/templates/firefox/browsers/mobile/android.html
  springfield/firefox/templates/firefox/browsers/mobile/ios.html
  springfield/firefox/templates/firefox/features/tips/tips.html
  springfield/firefox/templates/firefox/includes/mozilla-account-promo.html
  springfield/firefox/templatetags/misc.py
  springfield/firefox/tests/test_helper_misc.py
  springfield/settings/appstores.py
  springfield/settings/base.py
  tests/unit/spec/base/fxa-product-button.js
Labels: Awaiting Review

#295 Fix site details on global root and locale page
  springfield/base/templates/404-locale.html
  springfield/base/templates/base/locales.html
Labels: P2

#333 Add heading anchors to release notes
  springfield/firefox/templates/firefox/releases/notes.html
Labels: Frontend

#351 update /new page with new copy for all languages (mozilla/bedrock#16333)
  l10n/en-US/firefox/download/home.ftl
  l10n/en/firefox/download/desktop.ftl
  l10n/en/firefox/download/home.ftl
  media/css/firefox/home-ie8.scss
  media/css/firefox/home-ie9.scss
  media/css/firefox/home.scss
  media/img/firefox/home/meta-img-en.png
  media/img/firefox/home/meta-img-es.png
  media/img/firefox/home/meta-img-global.png
  media/js/firefox/home.js
  media/static-bundles.json
  springfield/firefox/templates/firefox/browsers/desktop/base.html
  springfield/firefox/templates/firefox/browsers/desktop/linux.html
  springfield/firefox/templates/firefox/browsers/desktop/mac.html
  springfield/firefox/templates/firefox/browsers/desktop/windows.html
  springfield/firefox/templates/firefox/download/desktop/download.html
  springfield/firefox/templates/firefox/download/home.html
  springfield/firefox/tests/test_views.py
  springfield/firefox/views.py
  tests/playwright/specs/products/firefox/firefox-download.spec.js
Labels: P1, Awaiting Review

#322 Update mobile QR codes to FXC URLs
  springfield/firefox/templates/firefox/browsers/mobile/get-app.html
  springfield/firefox/templates/firefox/browsers/mobile/includes/s2d-focus.html
Labels: P2, Awaiting Review

#368 fix nav content horizontal shift (fix #365)
  media/css/m24/components/navigation-refresh.scss
  springfield/base/templates/includes/navigation/nav-cta.html
Labels: Frontend, Awaiting Review
