Repository mozmeao/springfield, pull requests merged in 2025-09, with the labels that each got.

#462 Optimize images for ios summarizer
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-endless-webpages-1100.png
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-endless-webpages-500.png
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-endless-webpages-800.png
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-hero-animation-poster.png
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-hero-phone-shell-1100.png
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-hero-phone-shell-500.png
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-hero-phone-shell-800.png
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-screenshot-1100.png
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-screenshot-500.png
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-screenshot-800.png
Labels: Frontend, Needs Review

#461 Replace filtred SVG with CSS gradient #444
  media/css/firefox/ios-summarizer.scss
  media/img/firefox/browsers/mobile/ios/shake-to-summarize-gradient-bg.svg
  springfield/firefox/templates/firefox/landing/ios-summarizer.html
Labels: Frontend, Needs Review

#479 Adding product page id (ppid) support
  springfield/firefox/templates/firefox/landing/ios-summarizer.html
  springfield/firefox/templatetags/misc.py
  springfield/firefox/tests/test_helper_misc.py
Labels: P1, Needs Review

#480 Fix ja-JP-mac ESR115 download in unsupported macro
  springfield/firefox/templates/firefox/includes/download-unsupported.html
  springfield/firefox/templates/firefox/includes/macros.html
Labels: frontend, Needs Review, L10n

#496 Fix download tests by restricting the selector only to page section content
  tests/functional/conftest.py
Labels: Needs Review

#491 Pin sass at 1.91.0 until mozilla/protocol#982
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: P1, Needs Review

#486 Add ESR Linux/ARM64 builds to firefox/all
  springfield/firefox/firefox_details.py
  springfield/firefox/tests/test_firefox_all.py
  springfield/firefox/views.py
Labels: Needs Review
